### ISSUE TITLE
When Clicking A Popup Unclear That Transaction Went Thought

### ISSUE THREAD

**Issue by codingshot** [MinorityProgrammers/MagicBuild#19]
**Describe the bug**
When you click a form, you cant tell if on chain transaction was succesfull as popup stays or there is no indication that something succesful happened like a transaction link. 

**To Reproduce**
1. Click export and save
2. Or add client

**Expected behavior**
- the popup to close
- or a link to the component or client produce (When save maybe generate relative path based on the component saved to user data tree for the them to check) if getting a response is difficult

**Screenshots**
Popup wont go away
![Image](https://github.com/MinorityProgrammers/MagicBuild/assets/45281667/a20ec168-f110-42f4-a89c-d15234252a58)

Already uploaded 
![Image](https://github.com/MinorityProgrammers/MagicBuild/assets/45281667/70ecfc30-e93f-40e5-9765-b8cc16d1dce1)

**Comment by kurodenjiro** [comment]
![image](https://github.com/MinorityProgrammers/MagicBuild/assets/26534614/63a98578-4296-461f-9ca3-e9ef53bdec29)
After exporting, the path will be displayed for users to access
