### ISSUE TITLE
Call Methods Showing Up As View Method

### ISSUE THREAD

**Issue by codingshot** [MinorityProgrammers/MagicBuild#23]
**Describe the bug**
Some call methods are showing up as view method

**To Reproduce**
1. Created nft.genadrop.near contract
2. Exported component
3. Ex; look to nft_mint

**Expected behavior**
Show a form that takes in nft metdata

![Image](https://github.com/MinorityProgrammers/MagicBuild/assets/45281667/d2c00f55-ef25-4f53-a654-f50db6150eb1)

**Comment by kurodenjiro** [comment]
fixed
