### ISSUE TITLE
Display tabs to review exported components

### ISSUE THREAD

**Issue by kurodenjiro** [MinorityProgrammers/MagicBuild#5]
After creating the form and exporting the component. There is a tab where you can review the exported components

**Comment by codingshot** [comment]
should filter by deployed by magicbuild tag in metadata

**Comment by kurodenjiro** [comment]
![image](https://github.com/MinorityProgrammers/MagicBuild/assets/26534614/6bcf68f1-63cf-430f-b356-855f7df63ac8)
Added tabs to display exported lists
